version: '3.8'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    depends_on:
      - redis
    environment:
      - APP_ENV=local
      - REDIS_HOST=redis
      - APP_KEY=base64:

  redis:
    image: redis:alpine
